### ISSUE TITLE
Not concurrency safe?

### ISSUE THREAD

**Issue by awenborar** [gen2brain/avif#1]
I'm converting avif images to jpeg using the following code:
```
func FromAvif(r io.Reader) (AwenImage, error) {
	aimg := AwenImage{}

	img, err := avif.Decode(r)
	if err != nil {
		return aimg, err
	}

	buf := bytes.Buffer{}
	j.Encode(&buf, img, &DefaultJpegOptions)
	aimg.Buffer = buf.Bytes()
	aimg.MimeType = "image/jpeg"
	return aimg, nil
}
```
This works if the function is called sequentially but if I call this function concurrently I receive panics.
The panic error is too verbose and I'm not able to pinpoint to the core error.

PS - Great work on the library!

**Comment by gen2brain** [comment]
If you want to use it concurrently initialize it first (I should probably add Initialize()) with some dummy data, you can use io.Discard, ignore errors, etc. and then you can use it concurrently. The Wazero docs clearly state that this can happen when concurrently initializing the same runtime, and my usage is such that I don't want to do that unconditionally in init().

**Comment by awenborar** [comment]
I updated my `func` to run the first call with a lock. 
Ran 10 images in concurrent batches of 2 - (0,1) then (2, 3) .... The first batch succeeded successfully as it executed sequentially. Now assuming the first batch did the initialization, the second batch should have succeeded, but it didn't.

```
var avifMw = sync.RWMutex{}
var avifInitialized = false

func FromAvif(r io.Reader) (AwenImage, error) {
	if !avifInitialized {
		avifMw.Lock()
		defer func() {
			avifInitialized = true
			avifMw.Unlock()
		}()
	}

	aimg := AwenImage{}

	img, err := avif.Decode(r)
	if err != nil {
		return aimg, err
	}

	buf := bytes.Buffer{}
	j.Encode(&buf, img, &DefaultJpegOptions)
	aimg.Buffer = buf.Bytes()
	aimg.MimeType = "image/jpeg"
	return aimg, nil
}
```

I'm refactoring my flow to run all sequentially for now 👍

**Comment by awenborar** [comment]
Tried the following:
```
func init() {
	_, err := FromAvif(bytes.NewBuffer([]byte{}))
	log.Println("avif init expected err", err)
}

func FromAvif(r io.Reader) (AwenImage, error) {
	aimg := AwenImage{}

	img, err := avif.Decode(r)
	if err != nil {
		return aimg, err
	}

	buf := bytes.Buffer{}
	j.Encode(&buf, img, &DefaultJpegOptions)
	aimg.Buffer = buf.Bytes()
	aimg.MimeType = "image/jpeg"
	return aimg, nil
}
```
This doesn't work either

**Comment by DTreshy** [comment]
i have the same problem even after initializing, running it in goroutines ends up in panic

```
func Initialize() error {
	initFile, err := os.ReadFile("config/init.avif")
	if err != nil {
		return fmt.Errorf("error reading init.avif: %w", err)
	}

	img, err := avif.Decode(bytes.NewReader(initFile))
	if err != nil {
		return fmt.Errorf("error initializing avif decoder: %w", err)
	}

	var buf bytes.Buffer
	if err := avif.Encode(&buf, img); err != nil {
		return fmt.Errorf("error initializing avif encoder: %w", err)
	}

	return nil
}
```

**Comment by gen2brain** [comment]
This is fixed in https://github.com/gen2brain/avif/commit/b16bd1d8986bc36197e50f5b08cbb8f7b2275584. Now it will instantiate the module on every invocation, it will use more resources (more allocations) but can be safely called concurrently.
